services:
 homepage:
  image: ${HOME_IMAGE}
  restart: unless-stopped
  ports: ["8080:80"]
 frontend:
  image: ${FRONTEND_IMAGE}
  restart: unless-stopped
  ports: ["8081:80"]
 backend:
  image: ${BACKEND_IMAGE}
  restart: unless-stopped
  ports: ["4000:4000"]
  environment:
   NODE_ENV: production
   PORT: 4000
   MONGODB_URI: ${MONGODB_URI}
   REDIS_URL: ${REDIS_URL}
   JWT_SECRET: ${JWT_SECRET}
   FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}